version: "3"
services:
  php:
    build: 
      context: .
      dockerfile: Dockerfile-php
    ports:
      - '80:80'
    volumes:
      - ./src/web:/var/www/html
      - ./apache.conf:/etc/apache2/sites-available/
      - ./php.ini:/etc/php/7.4/apache2/
  # api:
  #   build: 
  #     context: .
  #     dockerfile: Dockerfile-api
  #   ports:
  #   - "5000:5100"
  #   # - "1883:1883"
  #   env_file: ./src/server/.env
  #   restart: unless-stopped
  #   expose:
  #     - 1883
        
  # mqtt:
  #   build: 
  #     context: .
  #     dockerfile: Dockerfile-mqtt
  #   network_mode: bridge
  #   expose:
  #     - 1883
  #   ports:
  #   - 1883:1883
  #   restart: unless-stopped
