FROM python:3

RUN pip install --upgrade pip
RUN pip install paho-mqtt
RUN pip install python-dotenv

COPY ./src/server/subscriber.py subscriber.py
COPY ./src/server/database_control.py database_control.py
COPY ./src/server/util.py util.py
COPY ./src/server/.env .env
COPY ./src/server/database database/
COPY ./src/server/logs logs/

CMD ["python3","subscriber.py"]