FROM python:3

RUN pip install --upgrade pip
RUN pip install flask

COPY ./src/server/database_control.py database_control.py
COPY ./src/server/publisher.py publisher.py
COPY ./src/server/api.py api.py
COPY ./src/server/database database/

CMD ["python3","api.py"]